/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmEntriMember.java
 *
 * Created on 15-Jun-2011, 16:40:39
 */
package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.util.formSystematization;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ataherster
 */
public class frmEntriMember extends javax.swing.JDialog {

    /** Creates new form frmEntriMember */
    public frmEntriMember(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initData();
               
        formSystematization.CenterScreen(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMemID = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtHP = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        dcTanggalLahir = new com.toedter.calendar.JDateChooser();
        dcTanggalMasuk = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Tanggal Lahir :");

        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Nama :");

        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Member ID :");

        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("HP :");

        txtMemID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMemIDFocusGained(evt);
            }
        });
        txtMemID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMemIDKeyPressed(evt);
            }
        });

        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });

        txtHP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHPFocusGained(evt);
            }
        });
        txtHP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHPKeyPressed(evt);
            }
        });

        btnSimpan.setText("Simpan Biodata Member");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal & Kembali ke Form Member");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        dcTanggalLahir.setDateFormatString("dd-MM-yyyy");

        dcTanggalMasuk.setDateFormatString("dd-MM-yyyy");

        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Tanggal Masuk :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNama)
                            .addComponent(txtMemID, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(dcTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dcTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBatal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dcTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(dcTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMemIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMemIDFocusGained
        txtMemID.setSelectionStart(0);
}//GEN-LAST:event_txtMemIDFocusGained

    private void txtMemIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMemIDKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtMemIDKeyPressed

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtHPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHPFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPFocusGained

    private void txtHPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHPKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHPKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            Insert_Member();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frmEntriKaryawan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "Error : Insert_Member()", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
}//GEN-LAST:event_btnBatalActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private com.toedter.calendar.JDateChooser dcTanggalLahir;
    private com.toedter.calendar.JDateChooser dcTanggalMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtHP;
    private javax.swing.JTextField txtMemID;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables

    
    
    Statement stmMember;
    PreparedStatement stmInsertMember;

    Statement stmGetData;
    ResultSet rsGetData;

    void initData (){
        try {
            stmMember=Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            init_PreparedStatement();
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex, "Error : initData", JOptionPane.ERROR_MESSAGE);
        }

    }

    void init_PreparedStatement () throws SQLException {
        stmInsertMember=Main.data.getActiveConnection().prepareStatement
                ("SELECT INSERT_MEMBER(?, ?, ?, ?, ?)");
    }

    void Insert_Member () throws SQLException {

        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

        stmInsertMember.setObject(1, txtMemID.getText());
        stmInsertMember.setObject(2, txtNama.getText());
        stmInsertMember.setObject(3, txtHP.getText());
        stmInsertMember.setObject(4, sd.format(dcTanggalLahir.getDate()));
        stmInsertMember.setObject(5, sd.format(dcTanggalMasuk.getDate()));
        
        stmInsertMember.execute();
    }
}
