/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmEntriKaryawan.java
 *
 * Created on Jan 30, 2010, 10:50:46 AM
 */

package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.util.formSystematization;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author User
 */
public class frmEntriKaryawan extends javax.swing.JDialog {

    /** Creates new form frmEntriKaryawan */
    public frmEntriKaryawan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        initData();

        formSystematization.CenterScreen(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cboStatusKawin = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        chkAktif = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextPane();
        txtPendidikan = new javax.swing.JTextField();
        txtTempatLahir = new javax.swing.JTextField();
        txtIDKaryawan = new javax.swing.JFormattedTextField();
        txtNamaKaryawan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtGajiPokok = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPersen = new javax.swing.JFormattedTextField();
        jLabel28 = new javax.swing.JLabel();
        txtTransportasi = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTjgKesehatan = new javax.swing.JFormattedTextField();
        txtTjgIstri = new javax.swing.JFormattedTextField();
        txtTjgAnak = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNamaPendek = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        dcTanggalMasuk = new com.toedter.calendar.JDateChooser();
        dcTanggalLahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setForeground(new java.awt.Color(0, 153, 51));
        jLabel4.setText("Alamat :");

        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Status Kawin :");

        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Nama Karyawan :");

        cboStatusKawin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Belum Kawin", "Kawin", "Janda", "Duda" }));
        cboStatusKawin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboStatusKawinKeyPressed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("ID Karyawan :");

        chkAktif.setSelected(true);
        chkAktif.setText("Karyawan Aktif");
        chkAktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAktifActionPerformed(evt);
            }
        });

        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        txtPendidikan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPendidikanFocusGained(evt);
            }
        });
        txtPendidikan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPendidikanKeyPressed(evt);
            }
        });

        txtTempatLahir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTempatLahirFocusGained(evt);
            }
        });
        txtTempatLahir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTempatLahirKeyPressed(evt);
            }
        });

        txtIDKaryawan.setEditable(false);

        txtNamaKaryawan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaKaryawanFocusGained(evt);
            }
        });
        txtNamaKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKaryawanKeyPressed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(0, 153, 51));
        jLabel6.setText("Pendidikan :");

        jLabel3.setForeground(new java.awt.Color(0, 153, 51));
        jLabel3.setText("Tempat / Tgl. Lahir :");

        txtGajiPokok.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtGajiPokok.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGajiPokok.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGajiPokokFocusGained(evt);
            }
        });
        txtGajiPokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGajiPokokKeyPressed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Gaji Pokok :");

        jLabel30.setForeground(new java.awt.Color(0, 153, 51));
        jLabel30.setText("%");

        txtPersen.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtPersen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPersen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPersenFocusGained(evt);
            }
        });
        txtPersen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPersenKeyPressed(evt);
            }
        });

        jLabel28.setForeground(new java.awt.Color(0, 153, 51));
        jLabel28.setText("Persen :");

        txtTransportasi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtTransportasi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTransportasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTransportasiKeyPressed(evt);
            }
        });

        jLabel17.setForeground(new java.awt.Color(0, 153, 51));
        jLabel17.setText("Tunjangan Transportasi :");

        txtTjgKesehatan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtTjgKesehatan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTjgKesehatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTjgKesehatanKeyPressed(evt);
            }
        });

        txtTjgIstri.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtTjgIstri.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTjgIstri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTjgIstriKeyPressed(evt);
            }
        });

        txtTjgAnak.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtTjgAnak.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTjgAnak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTjgAnakKeyPressed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(0, 153, 51));
        jLabel23.setText("Tunjangan Kesehatan :");

        jLabel19.setForeground(new java.awt.Color(0, 153, 51));
        jLabel19.setText("Tunjangan Istri :");

        jLabel21.setForeground(new java.awt.Color(0, 153, 51));
        jLabel21.setText("Tunjangan Anak :");

        btnSimpan.setText("Simpan Biodata Karyawan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal & Kembali ke Form Karyawan");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Nama Pendek :");

        txtNamaPendek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaPendekFocusGained(evt);
            }
        });
        txtNamaPendek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaPendekKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11));
        jLabel8.setText(" ** Tidak boleh sama dengan Karyawan Lain");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("*");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("*");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("*");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel13.setText("*");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("*");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel15.setText("*");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel16.setText("*");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel18.setText("*");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel20.setText("*");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel22.setText("*");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel24.setText("*");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel25.setText("Catatan :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel26.setText("* - Field / Kolom harus diisi");

        dcTanggalMasuk.setDateFormatString("dd-MM-yyyy");

        dcTanggalLahir.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(9, 9, 9)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel19)
                                                        .addComponent(jLabel21)
                                                        .addComponent(jLabel23)))
                                                .addComponent(jLabel17))
                                            .addComponent(jLabel28))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTjgIstri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addComponent(txtTjgAnak, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addComponent(txtTransportasi, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addComponent(txtTjgKesehatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSimpan)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnBatal))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtPersen, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel16))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(chkAktif)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                                .addComponent(dcTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel6))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGajiPokok, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txtTempatLahir, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dcTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(cboStatusKawin, 0, 360, Short.MAX_VALUE)
                                            .addComponent(txtPendidikan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIDKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtNamaPendek, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel8)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel26)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNamaPendek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtTempatLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(dcTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboStatusKawin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(txtGajiPokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPersen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel16)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTransportasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTjgIstri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTjgAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTjgKesehatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAktif)
                            .addComponent(dcTanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSimpan)
                            .addComponent(btnBatal)))
                    .addComponent(jLabel12))
                .addGap(4, 4, 4)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboStatusKawinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboStatusKawinKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboStatusKawinKeyPressed

    private void txtNamaKaryawanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaKaryawanFocusGained
        txtNamaKaryawan.setSelectionStart(0);
}//GEN-LAST:event_txtNamaKaryawanFocusGained

    private void txtNamaKaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKaryawanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNamaKaryawanKeyPressed

    private void txtTempatLahirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTempatLahirFocusGained
        txtTempatLahir.setSelectionStart(0);
}//GEN-LAST:event_txtTempatLahirFocusGained

    private void txtTempatLahirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatLahirKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtTempatLahirKeyPressed

    private void txtPendidikanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPendidikanFocusGained
        txtPendidikan.setSelectionStart(0);
}//GEN-LAST:event_txtPendidikanFocusGained

    private void txtPendidikanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPendidikanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtPendidikanKeyPressed

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed

}//GEN-LAST:event_txtAlamatKeyPressed

    private void chkAktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAktifActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_chkAktifActionPerformed

    private void txtTransportasiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTransportasiKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtTransportasiKeyPressed

    private void txtTjgIstriKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTjgIstriKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtTjgIstriKeyPressed

    private void txtTjgAnakKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTjgAnakKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtTjgAnakKeyPressed

    private void txtTjgKesehatanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTjgKesehatanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtTjgKesehatanKeyPressed

    private void txtGajiPokokFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGajiPokokFocusGained

}//GEN-LAST:event_txtGajiPokokFocusGained

    private void txtGajiPokokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGajiPokokKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtGajiPokokKeyPressed

    private void txtPersenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPersenFocusGained
        // TODO add your handling code here:
}//GEN-LAST:event_txtPersenFocusGained

    private void txtPersenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPersenKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtPersenKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            Insert_Karyawan();
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frmEntriKaryawan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "Error : Insert_Karyawan()", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNamaPendekFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaPendekFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaPendekFocusGained

    private void txtNamaPendekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPendekKeyPressed
        formSystematization.nextfocus(evt);
    }//GEN-LAST:event_txtNamaPendekKeyPressed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    Statement stmKaryawan;
    PreparedStatement stmInsertKaryawan;

    Statement stmGetData;
    ResultSet rsGetData;

    void initData (){
        try {
            stmKaryawan=Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            init_PreparedStatement();
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex, "Error : initData", JOptionPane.ERROR_MESSAGE);
        }

    }

    void init_PreparedStatement () throws SQLException {
        stmInsertKaryawan=Main.data.getActiveConnection().prepareStatement
                ("SELECT INSERT_KARYAWAN (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    }

    void Insert_Karyawan () throws SQLException {

        SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");

        stmInsertKaryawan.setObject(1, txtNamaKaryawan.getText());
        stmInsertKaryawan.setObject(2, sd.format(dcTanggalLahir.getDate()));
        stmInsertKaryawan.setObject(3, txtTempatLahir.getText());
        stmInsertKaryawan.setObject(4, txtAlamat.getText());
        stmInsertKaryawan.setObject(5, cboStatusKawin.getSelectedItem());
        stmInsertKaryawan.setObject(6, txtPendidikan.getText());

        stmInsertKaryawan.setObject(7, chkAktif.isSelected());

        stmInsertKaryawan.setObject(8, txtGajiPokok.getValue());
        stmInsertKaryawan.setObject(9, txtTransportasi.getValue());
        stmInsertKaryawan.setObject(10, txtTjgIstri.getValue());
        stmInsertKaryawan.setObject(11, txtTjgAnak.getValue());
        stmInsertKaryawan.setObject(12, txtTjgKesehatan.getValue());

        stmInsertKaryawan.setObject(13, txtNamaPendek.getText());
        stmInsertKaryawan.setObject(14, txtPersen.getValue());

        
        
        stmInsertKaryawan.setObject(15, sd.format(dcTanggalMasuk.getDate()));
        
        stmInsertKaryawan.execute();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox cboStatusKawin;
    private javax.swing.JCheckBox chkAktif;
    private com.toedter.calendar.JDateChooser dcTanggalLahir;
    private com.toedter.calendar.JDateChooser dcTanggalMasuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtAlamat;
    private javax.swing.JFormattedTextField txtGajiPokok;
    private javax.swing.JFormattedTextField txtIDKaryawan;
    private javax.swing.JTextField txtNamaKaryawan;
    private javax.swing.JTextField txtNamaPendek;
    private javax.swing.JTextField txtPendidikan;
    private javax.swing.JFormattedTextField txtPersen;
    private javax.swing.JTextField txtTempatLahir;
    private javax.swing.JFormattedTextField txtTjgAnak;
    private javax.swing.JFormattedTextField txtTjgIstri;
    private javax.swing.JFormattedTextField txtTjgKesehatan;
    private javax.swing.JFormattedTextField txtTransportasi;
    // End of variables declaration//GEN-END:variables

}
