/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmOrderBarang.java
 *
 * Created on Feb 9, 2010, 5:43:46 PM
 */

package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.setting.Setting;
import com.salon.util.MyStripRenderer;
import com.salon.util.formSystematization;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author User
 */
public class frmOrderBarang extends javax.swing.JFrame {

    /** Creates new form frmOrderBarang */
    public frmOrderBarang() {
        initComponents();
    }

    String OrderStatus="";
    
    Object OrderID;
    Statement stmOrder;
    PreparedStatement stmInsertOrder;
    ResultSet rsOrder;

    Statement stmOrderDetail;
    ResultSet rsOrderDetail;
    PreparedStatement stmBayarOrder;
    PreparedStatement stmTerimaBarangOrder;

    static Object SupplierID=null;
    static Object BarangIDOrder;

    BigDecimal TotalHargaPerawatan;
    BigDecimal JumlahBayarPerawatan;

    BigDecimal TotalHargaBarang;
    BigDecimal JumlahBayarBarang;

    BigDecimal TotalHargaOrder;
    BigDecimal JumlahBayarOrder;

    Object MetodeID;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelOrderBarang = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtNamaPerusahaan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtJumlahBarangOrder = new javax.swing.JFormattedTextField();
        txtNamaBarangOrder = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        btnBrowseSupplier = new javax.swing.JButton();
        btnBrowseBarang = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtHargaBarangOrder = new javax.swing.JFormattedTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtOngkosKirim = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        txtDiscountOrder = new javax.swing.JFormattedTextField();
        jLabel41 = new javax.swing.JLabel();
        btnOrder = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabelOrder = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelOrderDetail = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtHargaBayarOrder = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        chkCashOrder = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        txtMetode = new javax.swing.JTextField();
        btnBrowseMetode = new javax.swing.JButton();
        txtJumlahBayarOrder = new javax.swing.JFormattedTextField();
        btnBayarOrder = new javax.swing.JButton();
        btnTerimaBarang = new javax.swing.JButton();
        panelPenjualan1 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JFormattedTextField();
        txtTotalBayar = new javax.swing.JFormattedTextField();
        txtBankOrder = new javax.swing.JFormattedTextField();
        jLabel81 = new javax.swing.JLabel();
        txtRekOrder = new javax.swing.JFormattedTextField();
        jLabel83 = new javax.swing.JLabel();
        txtSisa = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel20.setForeground(new java.awt.Color(0, 153, 51));
        jLabel20.setText("Nama Perusahaan :");

        txtNamaPerusahaan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaPerusahaanKeyPressed(evt);
            }
        });

        jLabel21.setForeground(new java.awt.Color(0, 153, 51));
        jLabel21.setText("Nama Barang :");

        txtJumlahBarangOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahBarangOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtJumlahBarangOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahBarangOrderKeyPressed(evt);
            }
        });

        txtNamaBarangOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaBarangOrderKeyPressed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(0, 153, 51));
        jLabel23.setText("Jumlah Barang :");

        btnBrowseSupplier.setText("..");
        btnBrowseSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseSupplierActionPerformed(evt);
            }
        });

        btnBrowseBarang.setText("..");
        btnBrowseBarang.setMaximumSize(new java.awt.Dimension(23, 23));
        btnBrowseBarang.setMinimumSize(new java.awt.Dimension(23, 23));
        btnBrowseBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(2, 2, 2)
                .addComponent(txtNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnBrowseSupplier))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel21)
                .addGap(2, 2, 2)
                .addComponent(txtNamaBarangOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnBrowseBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel23)
                .addGap(2, 2, 2)
                .addComponent(txtJumlahBarangOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel20))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtNamaPerusahaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBrowseSupplier))
                .addGap(1, 1, 1)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel21))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtNamaBarangOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBrowseBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel23))
                    .addComponent(txtJumlahBarangOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        txtHargaBarangOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHargaBarangOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtHargaBarangOrder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHargaBarangOrderFocusGained(evt);
            }
        });
        txtHargaBarangOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHargaBarangOrderKeyPressed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(0, 153, 51));
        jLabel32.setText("Ongkos Kirim :");

        jLabel22.setForeground(new java.awt.Color(0, 153, 51));
        jLabel22.setText("Harga Barang :");

        txtOngkosKirim.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOngkosKirim.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtOngkosKirim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOngkosKirimFocusGained(evt);
            }
        });
        txtOngkosKirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOngkosKirimKeyPressed(evt);
            }
        });

        jLabel42.setForeground(new java.awt.Color(0, 153, 51));
        jLabel42.setText("Discount / % :");

        txtDiscountOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDiscountOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        txtDiscountOrder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDiscountOrderFocusGained(evt);
            }
        });
        txtDiscountOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDiscountOrderKeyPressed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel41.setText("%");

        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnOrder.setText("Transaksi");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel32)
                .addGap(2, 2, 2)
                .addComponent(txtOngkosKirim, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(2, 2, 2)
                .addComponent(txtHargaBarangOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel42)
                .addGap(2, 2, 2)
                .addComponent(txtDiscountOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel41))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel32))
                    .addComponent(txtOngkosKirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel22))
                    .addComponent(txtHargaBarangOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel42))
                    .addComponent(txtDiscountOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel41)))
                .addGap(2, 2, 2)
                .addComponent(btnOrder))
        );

        tabelOrder.setFont(new java.awt.Font("Courier New", 0, 13));
        tabelOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelOrderMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tabelOrder);

        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Detail Order");

        tabelOrderDetail.setFont(new java.awt.Font("Courier New", 0, 13));
        tabelOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tabelOrderDetail);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 10));
        jLabel18.setText("*) Dikurangi Diskon Bila Ada");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jLabel18, gridBagConstraints);

        txtHargaBayarOrder.setForeground(new java.awt.Color(0, 0, 204));
        txtHargaBayarOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHargaBayarOrder.setFont(new java.awt.Font("Tahoma", 1, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel6.add(txtHargaBayarOrder, gridBagConstraints);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel17.setForeground(new java.awt.Color(0, 51, 255));
        jLabel17.setText("Total Bayar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jLabel17, gridBagConstraints);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Jumlah Bayar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jLabel19, gridBagConstraints);

        chkCashOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        chkCashOrder.setSelected(true);
        chkCashOrder.setText("Cash");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(chkCashOrder, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel25.setText("Metode Pembayaran :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel6.add(jLabel25, gridBagConstraints);

        txtMetode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMetodeKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel6.add(txtMetode, gridBagConstraints);

        btnBrowseMetode.setText("..");
        btnBrowseMetode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseMetodeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanel6.add(btnBrowseMetode, gridBagConstraints);

        txtJumlahBayarOrder.setForeground(new java.awt.Color(255, 0, 0));
        txtJumlahBayarOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtJumlahBayarOrder.setFont(new java.awt.Font("Tahoma", 1, 24));
        txtJumlahBayarOrder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJumlahBayarOrderFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJumlahBayarOrderFocusLost(evt);
            }
        });
        txtJumlahBayarOrder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahBayarOrderKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel6.add(txtJumlahBayarOrder, gridBagConstraints);

        btnBayarOrder.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnBayarOrder.setText("Bayar");
        btnBayarOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarOrderActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        jPanel6.add(btnBayarOrder, gridBagConstraints);

        btnTerimaBarang.setFont(new java.awt.Font("Tahoma", 1, 11));
        btnTerimaBarang.setText("Terima Barang");
        btnTerimaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerimaBarangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 12);
        jPanel6.add(btnTerimaBarang, gridBagConstraints);

        javax.swing.GroupLayout panelOrderBarangLayout = new javax.swing.GroupLayout(panelOrderBarang);
        panelOrderBarang.setLayout(panelOrderBarangLayout);
        panelOrderBarangLayout.setHorizontalGroup(
            panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 549, Short.MAX_VALUE)
                    .addGroup(panelOrderBarangLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addContainerGap())
            .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelOrderBarangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        panelOrderBarangLayout.setVerticalGroup(
            panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOrderBarangLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel11))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelOrderBarangLayout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(187, Short.MAX_VALUE)))
        );

        panelPenjualan1.setBorder(javax.swing.BorderFactory.createTitledBorder("Statistik Transaksi"));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel75.setText("Total :");

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel77.setText("Total Bayar :");

        jLabel78.setFont(new java.awt.Font("Tahoma", 1, 11));

        jLabel79.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel79.setText("Bank :");

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 11));

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotal.setText("0");
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 11));

        txtTotalBayar.setEditable(false);
        txtTotalBayar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalBayar.setText("0");
        txtTotalBayar.setFont(new java.awt.Font("Tahoma", 1, 11));

        txtBankOrder.setEditable(false);
        txtBankOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtBankOrder.setFont(new java.awt.Font("Tahoma", 1, 11));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel81.setText("No. Rekening :");

        txtRekOrder.setEditable(false);
        txtRekOrder.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtRekOrder.setFont(new java.awt.Font("Tahoma", 1, 11));

        jLabel83.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel83.setText("Sisa :");

        txtSisa.setEditable(false);
        txtSisa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSisa.setText("0");
        txtSisa.setFont(new java.awt.Font("Tahoma", 1, 11));

        javax.swing.GroupLayout panelPenjualan1Layout = new javax.swing.GroupLayout(panelPenjualan1);
        panelPenjualan1.setLayout(panelPenjualan1Layout);
        panelPenjualan1Layout.setHorizontalGroup(
            panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel78)
                    .addComponent(jLabel80)
                    .addGroup(panelPenjualan1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel75)
                                .addGap(4, 4, 4)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel77)
                                .addGap(4, 4, 4)
                                .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel83)
                                .addGap(4, 4, 4)
                                .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel79)
                                .addGap(4, 4, 4)
                                .addComponent(txtBankOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addComponent(jLabel81)
                                .addGap(4, 4, 4)
                                .addComponent(txtRekOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelPenjualan1Layout.setVerticalGroup(
            panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel78)
                    .addComponent(jLabel80)
                    .addGroup(panelPenjualan1Layout.createSequentialGroup()
                        .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel75))
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel77))
                            .addComponent(txtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel83))
                            .addComponent(txtSisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel79))
                            .addComponent(txtBankOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(panelPenjualan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPenjualan1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel81))
                            .addComponent(txtRekOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelOrderBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPenjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelOrderBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(panelPenjualan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaPerusahaanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPerusahaanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNamaPerusahaanKeyPressed

    private void txtJumlahBarangOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahBarangOrderKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtJumlahBarangOrderKeyPressed

    private void txtNamaBarangOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaBarangOrderKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNamaBarangOrderKeyPressed

    private void btnBrowseSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseSupplierActionPerformed
        SelectData supplier = new SelectData(this, true) {
            @Override
            public void Select() {
                SupplierID=tabel.getValueAt(tabel.getSelectedRow(), 0);
                txtNamaPerusahaan.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
                txtBankOrder.setText(tabel.getValueAt(tabel.getSelectedRow(), 2).toString());
                txtRekOrder.setText(tabel.getValueAt(tabel.getSelectedRow(), 3).toString());
                dispose();
            }
        };
        supplier.setQuery("SELECT SUPPLIERID, NAMAPERUSAHAAN, BANK, NOREK FROM SUPPLIER() ORDER BY NAMAPERUSAHAAN");
        supplier.LoadData();
        supplier.show();
}//GEN-LAST:event_btnBrowseSupplierActionPerformed

    private void btnBrowseBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseBarangActionPerformed
        SelectData barang = new SelectData(this, true){
            @Override
            public void Select() {
                BarangIDOrder=tabel.getValueAt(tabel.getSelectedRow(), 0);
                txtNamaBarangOrder.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
                txtJumlahBarangOrder.requestFocus();
                dispose();

            }
        };
        barang.setQuery("SELECT BARANGID, NAMABARANG, HARGAJUAL FROM BARANG() ORDER BY NAMABARANG");
        barang.LoadData();
        barang.show();
}//GEN-LAST:event_btnBrowseBarangActionPerformed

    private void txtHargaBarangOrderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHargaBarangOrderFocusGained
        txtHargaBarangOrder.selectAll();
}//GEN-LAST:event_txtHargaBarangOrderFocusGained

    private void txtHargaBarangOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHargaBarangOrderKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtHargaBarangOrderKeyPressed

    private void txtOngkosKirimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOngkosKirimFocusGained
        txtOngkosKirim.selectAll();
}//GEN-LAST:event_txtOngkosKirimFocusGained

    private void txtOngkosKirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOngkosKirimKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtOngkosKirimKeyPressed

    private void txtDiscountOrderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDiscountOrderFocusGained
        txtDiscountOrder.selectAll();
}//GEN-LAST:event_txtDiscountOrderFocusGained

    private void txtDiscountOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDiscountOrderKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtDiscountOrderKeyPressed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        if (cekTransaksiOrder()) {
            try {
                Insert_Order();
                Select_Order();
                Select_OrderDetail();
                Blank_OrderDetail();
                txtJumlahBayarOrder.requestFocus();
            } catch (SQLException ex) {
                Logger.getLogger(frmBilling.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, ex, "error : btnTransaksiActionPerformed", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                Logger.getLogger(frmBilling.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, ex, "error : btnTransaksiActionPerformed", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Periksa kembali kelengkapan Form", "Err", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnOrderActionPerformed

    private void tabelOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelOrderMouseClicked
        try {
            Show_Order();
            txtJumlahBayarOrder.requestFocus();
        } catch (Exception ex) {
            Logger.getLogger(frmBilling.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex, "error : tabelOrderMouseClicked", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_tabelOrderMouseClicked

    private void txtMetodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMetodeKeyPressed
        // TODO add your handling code here:
}//GEN-LAST:event_txtMetodeKeyPressed

    private void btnBrowseMetodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseMetodeActionPerformed
        SelectData MetodePembayaran = new SelectData(this, true) {
            @Override
            public void Select() {
                MetodeID=tabel.getValueAt(tabel.getSelectedRow(), 0);
                txtMetode.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
                dispose();
            }
        };
        MetodePembayaran.setQuery("SELECT ID, PEMBAYARAN FROM JENISPEMBAYARAN");
        MetodePembayaran.LoadData();
        MetodePembayaran.show();
}//GEN-LAST:event_btnBrowseMetodeActionPerformed

    private void txtJumlahBayarOrderFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahBayarOrderFocusGained
        //        txtJumlahBayarOrder.selectAll();
}//GEN-LAST:event_txtJumlahBayarOrderFocusGained

    private void txtJumlahBayarOrderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahBayarOrderFocusLost
        TotalHargaOrder = (BigDecimal)txtHargaBayarOrder.getValue();
        JumlahBayarOrder = new BigDecimal((Long)txtJumlahBayarOrder.getValue());

        if (JumlahBayarOrder.intValueExact()>TotalHargaOrder.intValueExact()) {
            JumlahBayarOrder=TotalHargaOrder;
        }
}//GEN-LAST:event_txtJumlahBayarOrderFocusLost

    private void txtJumlahBayarOrderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahBayarOrderKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtJumlahBayarOrderKeyPressed

    private void btnBayarOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarOrderActionPerformed

}//GEN-LAST:event_btnBayarOrderActionPerformed

    private void btnTerimaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerimaBarangActionPerformed
        try {
            int result = JOptionPane.showConfirmDialog(this, "Anda telah menerima Barang ??", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (result==JOptionPane.YES_OPTION) {
                Terima_BarangOrder();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmBilling.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex, "btnTerimaBarangActionPerformed", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(frmBilling.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "error : btnTerimaBarangActionPerformed", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnTerimaBarangActionPerformed

    void initData () {
        try {
            stmOrder = Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmOrderDetail = Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);

            init_PreparedStatement();
        } catch (SQLException ex) {
            Logger.getLogger(frmOrderBarang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    void init_PreparedStatement () throws SQLException {

        stmInsertOrder=Main.data.getActiveConnection().prepareStatement("SELECT INSERT_ORDER (?,?,?,?,?,?::numeric,?::integer,?::integer)");
        stmBayarOrder=Main.data.getActiveConnection().prepareStatement("SELECT BAYARORDER (?,?::numeric,?,?::numeric)");
        stmTerimaBarangOrder=Main.data.getActiveConnection().prepareStatement("SELECT TERIMABARANG (?)");
    }

    void Select_Order () throws SQLException, Exception {
        rsOrder=stmOrder.executeQuery("SELECT WAKTU, NAMAPERUSAHAAN, ONGKOSKIRIM, HARGABAYAR, JUMLAHBAYAR,  HARGABAYAR-JUMLAHBAYAR AS SISA, " +
                "CASH, PEMBELIAN.BANK, PEMBELIAN.NOREK, ORDERID, PEMBELIAN.SUPPLIERID FROM PEMBELIAN(" + Setting.CabangID + ") INNER JOIN SUPPLIER USING(SUPPLIERID) " +
                "WHERE WAKTUTERIMA IS NULL OR HARGABAYAR>JUMLAHBAYAR");
        Main.data.JTableFill(tabelOrder, rsOrder);
        TableCellRenderer renderer = new MyStripRenderer(Color.BLACK, new Color(238,239,255));
        tabelOrder.setDefaultRenderer(Object.class, renderer);
    }

    void Insert_Order () throws SQLException {
        stmInsertOrder.setObject(1, Setting.CabangID);
        stmInsertOrder.setObject(2, OrderID);
        stmInsertOrder.setObject(3, SupplierID);
        stmInsertOrder.setObject(4, txtOngkosKirim.getValue());
        stmInsertOrder.setObject(5, BarangIDOrder);
        stmInsertOrder.setObject(6, txtHargaBarangOrder.getValue());
        stmInsertOrder.setObject(7, txtJumlahBarangOrder.getValue());
        stmInsertOrder.setObject(8, txtDiscountOrder.getValue());

        stmInsertOrder.execute();
    }

    void Show_Order () throws Exception {
        OrderID=tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 9);
        SupplierID=tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 10);
        txtNamaPerusahaan.setText(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 1).toString());
        txtOngkosKirim.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 2));
        txtHargaBayarOrder.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 5));
        txtJumlahBayarOrder.setValue(null);

        if (tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 6)!=null) {
            chkCashOrder.setSelected((Boolean)tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 6));
            chkCashOrder.setEnabled(false);
        } else {
            chkCashOrder.setEnabled(true);
            chkCashOrder.setSelected(true);
        }

        txtBankOrder.setText(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 7).toString());
        txtRekOrder.setText(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 8).toString());

        StatistikOrder();

        OrderStatus="UPDATE";
        Select_OrderDetail();
    }

    void Blank_Order () throws SQLException, Exception {
        OrderID=null;
        MetodeID=null;
        txtNamaPerusahaan.setText("");
        txtOngkosKirim.setValue(null);
        txtHargaBayarOrder.setValue(null);
        txtJumlahBayarOrder.setValue(null);
        Select_Order();
        Blank_OrderDetail();
    }

    void Select_OrderDetail () throws Exception {
        rsOrderDetail=stmOrderDetail.executeQuery("SELECT NAMABARANG, HARGA, JUMLAH, DISCOUNT " +
                "FROM DETAILPEMBELIAN() INNER JOIN BARANG() USING(BARANGID) WHERE ORDERID='" + OrderID + "'");
        Main.data.JTableFill(tabelOrderDetail, rsOrderDetail);
        TableCellRenderer renderer = new MyStripRenderer(Color.BLACK, new Color(238,239,255));
        tabelOrderDetail.setDefaultRenderer(Object.class, renderer);
    }

    void Show_OrderDetail () {

    }

    void Blank_OrderDetail ()throws Exception {
        BarangIDOrder=null;
        MetodeID=null;
        txtNamaBarangOrder.setText("");
        txtHargaBarangOrder.setValue(null);
        txtJumlahBarangOrder.setValue(null);
        txtDiscountOrder.setValue(null);
        Select_OrderDetail();
    }

    void Bayar_Order () throws SQLException {
        stmBayarOrder.setObject(1, OrderID);
        stmBayarOrder.setObject(2, JumlahBayarOrder);
        stmBayarOrder.setObject(3, chkCashOrder.isSelected());
        stmBayarOrder.setObject(4, MetodeID);

        stmBayarOrder.execute();
    }

    void Terima_BarangOrder () throws SQLException {
        stmTerimaBarangOrder.setObject(1, OrderID);
        stmTerimaBarangOrder.execute();
    }

    /*Object getTotalBayarOrder () throws SQLException {
        rsGetData=stmGetData.executeQuery("SELECT HARGABAYAR-JUMLAHBAYAR AS TOTAL FROM PEMBELIAN()" +
                " WHERE ORDERID='" + OrderID + "'");
        if (rsGetData.wasNull()) {
            return null;
        } else {
            rsGetData.next();
            return rsGetData.getBigDecimal("TOTAL");
        }
    }

    Object getJumlahBayarOrder () throws SQLException {
        rsGetData=stmGetData.executeQuery("SELECT JUMLAHBAYAR FROM PEMBELIAN()" +
                " WHERE ORDERID='" + OrderID + "'");
        if (rsGetData.wasNull()) {
            return null;
        } else {
            rsGetData.next();
            return rsGetData.getObject("JUMLAHBAYAR");
        }

    }*/

    Boolean cekBayarOrder () {
        if (MetodeID==null) {
            return false;
        } else {
            return true;
        }
    }

    Boolean cekTransaksiOrder () {
        if (txtJumlahBarangOrder.getValue()==null || txtOngkosKirim.getValue()==null || txtHargaBarangOrder.getValue()==null ||
                txtDiscountOrder.getValue()==null) {
            return false;
        } else {
            return true;
        }
    }

    void StatistikTransaksi () {

        jLabel79.setVisible(false);
        jLabel81.setVisible(false);
        txtBankOrder.setVisible(false);
        txtRekOrder.setVisible(false);
    }

    void StatistikOrder () {
        jLabel79.setVisible(true);
        jLabel81.setVisible(true);
        txtBankOrder.setVisible(true);
        txtRekOrder.setVisible(true);

        txtTotal.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 3));
        txtTotalBayar.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 4));
        txtSisa.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 5));
        txtBankOrder.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 7));
        txtRekOrder.setValue(tabelOrder.getValueAt(tabelOrder.getSelectedRow(), 8));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayarOrder;
    private javax.swing.JButton btnBrowseBarang;
    private javax.swing.JButton btnBrowseMetode;
    private javax.swing.JButton btnBrowseSupplier;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnTerimaBarang;
    private javax.swing.JCheckBox chkCashOrder;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel panelOrderBarang;
    private javax.swing.JPanel panelPenjualan1;
    private javax.swing.JTable tabelOrder;
    private javax.swing.JTable tabelOrderDetail;
    private javax.swing.JFormattedTextField txtBankOrder;
    static javax.swing.JFormattedTextField txtDiscountOrder;
    static javax.swing.JFormattedTextField txtHargaBarangOrder;
    private javax.swing.JFormattedTextField txtHargaBayarOrder;
    static javax.swing.JFormattedTextField txtJumlahBarangOrder;
    private javax.swing.JFormattedTextField txtJumlahBayarOrder;
    static javax.swing.JTextField txtMetode;
    static javax.swing.JTextField txtNamaBarangOrder;
    static javax.swing.JTextField txtNamaPerusahaan;
    static javax.swing.JFormattedTextField txtOngkosKirim;
    private javax.swing.JFormattedTextField txtRekOrder;
    private javax.swing.JFormattedTextField txtSisa;
    private javax.swing.JFormattedTextField txtTotal;
    private javax.swing.JFormattedTextField txtTotalBayar;
    // End of variables declaration//GEN-END:variables

}
