/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPendapatan.java
 *
 * Created on Feb 27, 2010, 11:49:34 PM
 */

package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.util.ReportAdministration;
import com.salon.util.formSystematization;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author User
 */
public class frmPendapatan extends javax.swing.JDialog {

    /** Creates new form frmPendapatan */
    public frmPendapatan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initData();
        formSystematization.CenterScreen(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPendapatan = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        btnPreviewPerawatan = new javax.swing.JButton();
        dcDari = new com.toedter.calendar.JDateChooser();
        dcSampai = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Total Pendapatan");

        jLabel1.setText("Dari Tanggal : ");

        jLabel2.setText("Sampai Tanggal : ");

        txtPendapatan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPendapatan.setFont(new java.awt.Font("Courier New", 1, 24));
        txtPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPendapatanActionPerformed(evt);
            }
        });
        txtPendapatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPendapatanKeyPressed(evt);
            }
        });

        jLabel3.setText("<html>Pendapatan didapatkan dari (Total Pendapatan Bersih dan Pengeluaran) ditambah (Pendapatan Karyawan dan Penarikan / Cash Bon)</html>");

        btnPreviewPerawatan.setText("Cetak Rincian Pendapatan");
        btnPreviewPerawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewPerawatanActionPerformed(evt);
            }
        });

        dcDari.setDateFormatString("dd-MM-yyyy");
        dcDari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcDariKeyPressed(evt);
            }
        });

        dcSampai.setDateFormatString("dd-MM-yyyy");
        dcSampai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dcSampaiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(dcDari, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addComponent(dcSampai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnPreviewPerawatan)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dcDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(dcSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addComponent(txtPendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(btnPreviewPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPendapatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPendapatanActionPerformed

    private void txtPendapatanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPendapatanKeyPressed
        formKeyboardSortcut(evt);
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {

            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

            String DariTanggal = df.format(dcDari.getDate());
            String SampaiTanggal = df.format(dcSampai.getDate());

            String sqlQuery = "SELECT SALON, KARYAWAN, SALON+KARYAWAN AS TOTAL FROM (SELECT " +

                "(SELECT CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END " +
                "FROM (SELECT SUM(DEBET)-SUM(KREDIT) AS SALDO " +
                "FROM MUTASIKEUANGAN WHERE IDKARYAWAN IN (SELECT DEFAULTACCOUNT()) AND (WAKTU::DATE BETWEEN '" + DariTanggal + "' AND '" + SampaiTanggal + "')) AS D) AS SALON, " +
                "" +
                "(SELECT CASE WHEN SALDO IS NULL THEN 0 ELSE SALDO END " +
                "FROM (SELECT SUM(KREDIT)-SUM(DEBET) AS SALDO " +
                "FROM MUTASIKEUANGAN WHERE IDKARYAWAN NOT IN (SELECT DEFAULTACCOUNT()) AND (WAKTU::DATE BETWEEN '" + DariTanggal + "' AND '" + SampaiTanggal + "')) AS D) AS KARYAWAN" +
                ") AS T";
            try {
                stmGetData = Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
                rsGetData=stmGetData.executeQuery(sqlQuery);
                if (rsGetData.next()) {
                    txtPendapatan.setValue(rsGetData.getObject(3));
                    formSystematization.nextfocus(evt);
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmPendapatan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, ex, "err : GetPendapatan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_txtPendapatanKeyPressed

    private void btnPreviewPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewPerawatanActionPerformed

        HashMap hm = new HashMap();
        String DariTanggal;
        String SampaiTanggal;

        String ReportFile = null;

        ReportFile = ReportAdministration.getReportFile() + "Pendapatan.jasper";
        
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DariTanggal = df.format(dcDari.getDate());
        SampaiTanggal = df.format(dcSampai.getDate());

        hm.put("drTanggal", DariTanggal);
        hm.put("smpTanggal", SampaiTanggal);

        try {
            ReportAdministration.printReport(Main.data.getActiveConnection(), ReportFile, hm, 0, 0, false);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPreviewPerawatanActionPerformed

    private void dcDariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcDariKeyPressed
        formSystematization.nextfocus(evt);
    }//GEN-LAST:event_dcDariKeyPressed

    private void dcSampaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dcSampaiKeyPressed
        formSystematization.nextfocus(evt);
    }//GEN-LAST:event_dcSampaiKeyPressed

    void initData () {

    }

    void formKeyboardSortcut (KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_ESCAPE : dispose();
                break;
        }
    }
    
    Statement stmGetData;
    ResultSet rsGetData;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreviewPerawatan;
    private com.toedter.calendar.JDateChooser dcDari;
    private com.toedter.calendar.JDateChooser dcSampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JFormattedTextField txtPendapatan;
    // End of variables declaration//GEN-END:variables

}
