/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPendapatanKaryawan.java
 *
 * Created on 30 Mar 10, 15:47:31
 */

package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.util.NumberRenderer;
import com.salon.util.ReportAdministration;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author User
 */
public class frmPendapatanKaryawan extends javax.swing.JPanel {

    /** Creates new form frmPendapatanKaryawan */
    public frmPendapatanKaryawan() {
        initComponents();
        initData();
    }

    Statement stmPendapatan;
    ResultSet rsPendapatan;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPendapatan = new javax.swing.JTable();
        btnCetak = new javax.swing.JButton();

        tabelPendapatan.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        tabelPendapatan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabelPendapatan.setRowHeight(20);
        jScrollPane1.setViewportView(tabelPendapatan);

        btnCetak.setText("Cetak Pendapatan Karyawan");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(btnCetak)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        HashMap hm = new HashMap();
        String ReportFile = null;
        ReportFile = ReportAdministration.getReportFile() + "pendapatankaryawan.jasper";

        try {
            ReportAdministration.printReport(Main.data.getActiveConnection(), ReportFile, hm, 0, 0, false);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    void initData (){

        tabelPendapatan.setAutoCreateRowSorter(true);
        try {
            stmPendapatan=Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            Select_Pendapatan();
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Error : initData", JOptionPane.ERROR_MESSAGE);
        }

    }

    void Select_Pendapatan () throws SQLException, Exception {
        rsPendapatan = stmPendapatan.executeQuery("SELECT IDKARYAWAN, NAMAKARYAWAN, NAMAPENDEK, PERSEN, " +
                "(SELECT SALDOACCOUNT(IDKARYAWAN)) AS PENDAPATAN FROM KARYAWAN " +
                "WHERE IDKARYAWAN NOT IN (SELECT DEFAULTACCOUNT()) AND STATUSAKTIF=TRUE");

        Main.data.JTableFill(tabelPendapatan, rsPendapatan);
        tabelPendapatan.getColumnModel().getColumn(3).setCellRenderer(new NumberRenderer());
        tabelPendapatan.getColumnModel().getColumn(4).setCellRenderer(new NumberRenderer());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPendapatan;
    // End of variables declaration//GEN-END:variables

}
