/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.util.MyStripRenderer;
import com.salon.util.NumberRenderer;
import com.salon.util.formSystematization;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author Thinkpad
 */
public class frmPersenStylish extends javax.swing.JDialog {

    /**
     * Creates new form frmPersenStylish
     */
    public frmPersenStylish(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        formSystematization.CenterScreen(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPersenStylish = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSesuaikanData = new javax.swing.JButton();
        txtIdKaryawan = new javax.swing.JTextField();
        txtNamaKaryawan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pengaturan Persen Stylish");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabelPersenStylish.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        tabelPersenStylish.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelPersenStylish);

        jLabel1.setText("Id Karyawan :");

        jLabel2.setText("Nama Karyawan :");

        btnSesuaikanData.setText("Sesuaikan Data Perawatan");
        btnSesuaikanData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSesuaikanDataActionPerformed(evt);
            }
        });

        txtIdKaryawan.setEnabled(false);

        txtNamaKaryawan.setEnabled(false);
        txtNamaKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 809, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaKaryawan)
                            .addComponent(txtIdKaryawan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSesuaikanData)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(btnSesuaikanData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSesuaikanDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSesuaikanDataActionPerformed
        try {
            Sesuaikan_data_perawatan();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Error : Update", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSesuaikanDataActionPerformed

    private void txtNamaKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKaryawanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        initData();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPersenStylish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPersenStylish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPersenStylish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPersenStylish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmPersenStylish dialog = new frmPersenStylish(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
        
        
    }

    Statement stmPersenStylish;
    PreparedStatement stmUpdatePersen;
    Statement stmSesuaikanData;
    ResultSet rs;
    
    void initData (){

        tabelPersenStylish.setAutoCreateRowSorter(true);
        try {
            stmPersenStylish=Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            stmSesuaikanData=Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            Select_PersenStylish();
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex, "Error : initData", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    void Sesuaikan_data_perawatan () throws SQLException, Exception {
        String defaultPersen = JOptionPane.showInputDialog(rootPane, "Masukkan Default persenstylish, nilai default ini akan di masukkan kedalam data yang disesuaikan");
        
        String sqlQuery="INSERT INTO PERSENSTYLISH (idkaryawan,kodeperawatan,persenstylish) " +
                                    "SELECT " + txtIdKaryawan.getText() + " as idkaryawan, KODEPERAWATAN, " + defaultPersen + " FROM PERAWATAN " +
                                    "WHERE STATUSAKTIF=TRUE AND kodeperawatan NOT IN (SELECT kodeperawatan FROM persenstylish WHERE idkaryawan=" +
                                    txtIdKaryawan.getText() + ")";
        
         try {                
                System.out.println(stmSesuaikanData.execute(sqlQuery));
                Select_PersenStylish();
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, ex, "Error : Update", JOptionPane.ERROR_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, ex, "Error : Update", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }

    void Select_PersenStylish () throws SQLException, Exception {
        
        rs=stmPersenStylish.executeQuery("SELECT id, ps.kodeperawatan, deskripsi, namaperawatan, ps.persenstylish " +
                                        "FROM persenstylish AS ps LEFT JOIN karyawan AS k ON ps.idkaryawan=k.idkaryawan " +
                                        "LEFT JOIN perawatan AS p ON ps.kodeperawatan=p.kodeperawatan " +
                                        "LEFT JOIN jenisperawatan AS jp on p.kodejenisperawatan=jp.kodejenisperawatan " +
                                        "WHERE ps.idkaryawan=" + txtIdKaryawan.getText() + " "
                                                + "ORDER BY DESKRIPSI, NAMAPERAWATAN");

        DefaultTableModel model;
        model = new DefaultTableModel() {
            
            Class[] type = new Class[] {
                Integer.class, Integer.class, String.class, String.class, Integer.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return type [columnIndex];
            }            
                       
            @Override
            public void fireTableCellUpdated(int row, int column) {
                super.fireTableCellUpdated(row, column);
                if (tabelPersenStylish.getValueAt(tabelPersenStylish.getSelectedRow(), 0)!=null) {
                    String  sqlQuery="";
                    
                    switch (column) {
                        case 2:return;
                        default :
                            
                            sqlQuery="UPDATE PERSENSTYLISH SET PERSENSTYLISH=? WHERE ID=" + tabelPersenStylish.getValueAt(tabelPersenStylish.getSelectedRow(), 0);
                    }
                    
                    try {
                        
                        stmUpdatePersen = Main.data.getActiveConnection().prepareStatement(sqlQuery);
                        stmUpdatePersen.setObject(1, tabelPersenStylish.getValueAt(tabelPersenStylish.getSelectedRow(), tabelPersenStylish.getSelectedColumn()));
                        
                        System.out.println(stmUpdatePersen.executeUpdate());
                        
                        Select_PersenStylish();
                    } catch (SQLException ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex, "Error : Update", JOptionPane.ERROR_MESSAGE);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, ex, "Error : Update", JOptionPane.ERROR_MESSAGE);
                    }

                }
            };

            @Override
            public boolean isCellEditable(int row, int column) {
                switch (column){
                    case 0:return false;
                    case 1:return false;
                    case 2:return false;
                    case 3:return false;
                    default:return true;
                }
            }
        };

        Main.data.JTableFill(tabelPersenStylish, (ResultSet) rs, model);
        TableCellRenderer renderer = new MyStripRenderer(Color.BLACK, new Color(238,239,255));
        tabelPersenStylish.setDefaultRenderer(Object.class, renderer);
        tabelPersenStylish.getColumnModel().getColumn(4).setCellRenderer(new NumberRenderer());

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSesuaikanData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPersenStylish;
    public javax.swing.JTextField txtIdKaryawan;
    public javax.swing.JTextField txtNamaKaryawan;
    // End of variables declaration//GEN-END:variables
}
