/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmRegistrasiTamu.java
 *
 * Created on Jan 27, 2010, 9:37:49 PM
 */

package com.salon.ui.form;

import com.salon.util.formSystematization;
import java.awt.Cursor;
import java.awt.Frame;
import java.awt.event.KeyEvent;

/**
 *
 * @author User
 */
public class frmRegistrasiTamu extends javax.swing.JDialog {

    /** Creates new form frmRegistrasiTamu */
    public frmRegistrasiTamu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        formSystematization.CenterScreen(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnRegis = new javax.swing.JButton();
        txtNamaTamu = new javax.swing.JTextField();
        txtTelp = new javax.swing.JTextField();
        txtNoAntrian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDMember = new javax.swing.JTextField();
        btnBrowseKaryawan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrasi Tamu");

        jLabel1.setText("Nama Tamu :");

        jLabel3.setText("No. Antrian :");

        jLabel2.setText("Telp / Hp :");

        btnBatal.setText("Batal Registrasi Tamu");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        btnBatal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnBatalKeyPressed(evt);
            }
        });

        btnRegis.setText("Registrasi Tamu");
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        btnRegis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRegisKeyPressed(evt);
            }
        });

        txtNamaTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaTamuKeyPressed(evt);
            }
        });

        txtTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelpKeyPressed(evt);
            }
        });

        txtNoAntrian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoAntrianKeyPressed(evt);
            }
        });

        jLabel4.setText("ID Member :");

        txtIDMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDMemberKeyPressed(evt);
            }
        });

        btnBrowseKaryawan.setText("jButton1");
        btnBrowseKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseKaryawanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowseKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnRegis)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNoAntrian, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(txtNamaTamu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                                    .addComponent(txtTelp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBrowseKaryawan, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIDMember)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNamaTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNoAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegis)
                    .addComponent(btnBatal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        RegisTamu();
}//GEN-LAST:event_btnRegisActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaTamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaTamuKeyPressed
        formKeyboardSortcut(evt);
        formSystematization.nextfocus(evt);
    }//GEN-LAST:event_txtNamaTamuKeyPressed

    private void txtTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelpKeyPressed
        formKeyboardSortcut(evt);
        formSystematization.nextfocus(evt);
    }//GEN-LAST:event_txtTelpKeyPressed

    private void txtNoAntrianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoAntrianKeyPressed
        formKeyboardSortcut(evt);
        formSystematization.nextfocus(evt);
    }//GEN-LAST:event_txtNoAntrianKeyPressed

    private void btnRegisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRegisKeyPressed
        formKeyboardSortcut(evt);
    }//GEN-LAST:event_btnRegisKeyPressed

    private void btnBatalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnBatalKeyPressed
        formKeyboardSortcut(evt);
    }//GEN-LAST:event_btnBatalKeyPressed

    private void txtIDMemberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDMemberKeyPressed
        formKeyboardSortcut(evt);
        
        if (FindMember()) {
            formSystematization.nextfocus(evt);
        }        
    }//GEN-LAST:event_txtIDMemberKeyPressed

    private void btnBrowseKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseKaryawanActionPerformed
        Show_Browse_Member();
    }//GEN-LAST:event_btnBrowseKaryawanActionPerformed

    void formKeyboardSortcut (KeyEvent e) {
        switch (e.getKeyCode()) {
            case KeyEvent.VK_ESCAPE : dispose();
                break;
        }
    }

    void Show_Browse_Member () {
        SelectData member=new SelectData(new Frame(), true) {

            @Override
            public void Select () {
                txtIDMember.setText(tabel.getValueAt(tabel.getSelectedRow(), 0).toString());
                txtNamaTamu.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
                txtTelp.setText(tabel.getValueAt(tabel.getSelectedRow(), 2).toString());
                dispose();
                txtNoAntrian.requestFocus();
            }

            @Override
            public void Search() throws Exception {
                setQuery("SELECT MEMID, NAMA, HP, TGLLAHIR, POIN FROM MEMBER "
                        + "WHERE NAMA ILIKE '%" + txtCari.getText().toString() + "%' "
                        + "ORDER BY NAMA");
                super.Search();
            }
            
        };
        member.setQuery("SELECT MEMID, NAMA, HP, TGLLAHIR, POIN FROM MEMBER ORDER BY NAMA");
        member.LoadData();
        member.show();
    }
    
    public void RegisTamu () {}
    
    public Boolean FindMember () {return true;}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    public static javax.swing.JButton btnBrowseKaryawan;
    private javax.swing.JButton btnRegis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JTextField txtIDMember;
    public javax.swing.JTextField txtNamaTamu;
    public javax.swing.JTextField txtNoAntrian;
    public javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables

}
