/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviewLaporan.java
 *
 * Created on 12-Mar-2009, 17:22:54
 */

package com.salon.ui.form;

import com.salon.launcher.Main;
import com.salon.util.ReportAdministration;
import java.awt.AWTException;
import java.awt.Frame;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author SAK
 */
public class PreviewLaporan extends javax.swing.JDialog {

    /** Creates new form PreviewLaporan */
    public PreviewLaporan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initData();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelKaryawan = new javax.swing.JPanel();
        txtNamaKaryawan = new javax.swing.JTextField();
        btnBrowseKaryawan = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        chkPerusahaan = new javax.swing.JCheckBox();
        btnPreviewMutasiKeuangan = new javax.swing.JButton();
        dcDari = new com.toedter.calendar.JDateChooser();
        dcSampai = new com.toedter.calendar.JDateChooser();
        btnPreviewMutasiDaftarKaryawan = new javax.swing.JButton();
        btnPendapatan = new javax.swing.JButton();
        btnPendapatanHarian = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preview Mutasi Keuangan");

        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mutasi Keuangan"));

        jLabel1.setText("Dari Tanggal : ");

        jLabel2.setText("Sampai Tanggal : ");

        panelKaryawan.setBorder(javax.swing.BorderFactory.createTitledBorder("Karyawan : "));

        txtNamaKaryawan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKaryawanKeyPressed(evt);
            }
        });

        btnBrowseKaryawan.setText("jButton1");
        btnBrowseKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseKaryawanActionPerformed(evt);
            }
        });

        jLabel12.setText("Stylish");

        javax.swing.GroupLayout panelKaryawanLayout = new javax.swing.GroupLayout(panelKaryawan);
        panelKaryawan.setLayout(panelKaryawanLayout);
        panelKaryawanLayout.setHorizontalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnBrowseKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelKaryawanLayout.setVerticalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addGroup(panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(btnBrowseKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkPerusahaan.setText("Mutasi Keungan Karyawan");
        chkPerusahaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPerusahaanActionPerformed(evt);
            }
        });

        btnPreviewMutasiKeuangan.setText("Preview Mutasi Keuangan");
        btnPreviewMutasiKeuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewMutasiKeuanganActionPerformed(evt);
            }
        });

        dcDari.setDateFormatString("dd-MM-yyyy");

        dcSampai.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcSampai, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(dcDari, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addComponent(panelKaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chkPerusahaan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(btnPreviewMutasiKeuangan)))
                .addContainerGap())
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(dcDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dcSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkPerusahaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreviewMutasiKeuangan))
        );

        btnPreviewMutasiDaftarKaryawan.setText("Preview Daftar Karyawan");
        btnPreviewMutasiDaftarKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewMutasiDaftarKaryawanActionPerformed(evt);
            }
        });

        btnPendapatan.setText("Rincian Pendapatan Karyawan");
        btnPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanActionPerformed(evt);
            }
        });

        btnPendapatanHarian.setText("Pendapatan Karyawan");
        btnPendapatanHarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendapatanHarianActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPendapatan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPreviewMutasiDaftarKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPendapatanHarian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreviewMutasiDaftarKaryawan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPendapatan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPendapatanHarian)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaKaryawanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKaryawanKeyPressed
        nextfocus(evt);
}//GEN-LAST:event_txtNamaKaryawanKeyPressed

    private void btnBrowseKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseKaryawanActionPerformed
        Show_Browse_Karyawan();
}//GEN-LAST:event_btnBrowseKaryawanActionPerformed

    private void chkPerusahaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPerusahaanActionPerformed
        txtNamaKaryawan.setText("");
        txtNamaKaryawan.setEnabled(chkPerusahaan.isSelected());
        btnBrowseKaryawan.setEnabled(chkPerusahaan.isSelected());
}//GEN-LAST:event_chkPerusahaanActionPerformed

    private void btnPreviewMutasiKeuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewMutasiKeuanganActionPerformed
        if (chkPerusahaan.isSelected()==false) {
            try {
                rsGetData = stmGetData.executeQuery("SELECT DEFAULTACCOUNT()");
                rsGetData.next();
                KaryawanID = rsGetData.getObject(1);
            } catch (SQLException ex) {
                Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, ex, "err : ", JOptionPane.ERROR_MESSAGE);
            }
        }

        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DariTanggal = df.format(dcDari.getDate());
        SampaiTanggal = df.format(dcSampai.getDate());
        
        HashMap hm = new HashMap();

        hm.put("idkaryawan", KaryawanID);
        hm.put("drtanggal", DariTanggal);
        hm.put("smptanggal", SampaiTanggal);
        hm.put("SUBREPORT_DIR", ReportAdministration.getReportFile());
        String ReportFile = null;

        if (chkPerusahaan.isSelected()==false) {
            ReportFile = ReportAdministration.getReportFile() + "mutasikeuangan.jasper";
        }else {
            ReportFile = ReportAdministration.getReportFile() + "mutasigaji.jasper";
        }
        
        try {
            ReportAdministration.runReport(Main.data.getActiveConnection(), ReportFile, hm);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPreviewMutasiKeuanganActionPerformed

    private void btnPreviewMutasiDaftarKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewMutasiDaftarKaryawanActionPerformed
        HashMap hm = new HashMap();
        String ReportFile=null;
        ReportFile = ReportAdministration.getReportFile() + "karyawan.jasper";
        try {
            ReportAdministration.runReport(Main.data.getActiveConnection(), ReportFile, hm);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPreviewMutasiDaftarKaryawanActionPerformed

    private void btnPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanActionPerformed
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DariTanggal = df.format(dcDari.getDate());
        SampaiTanggal = df.format(dcSampai.getDate());

        HashMap hm = new HashMap();

        hm.put("IdKaryawan", KaryawanID);
        hm.put("drTanggal", DariTanggal);
        hm.put("smpTanggal", SampaiTanggal);
        String ReportFile = null;

            ReportFile = ReportAdministration.getReportFile() + "TransaksiKaryawan.jasper";

        try {

            ReportAdministration.runReport(Main.data.getActiveConnection(), ReportFile, hm);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPendapatanActionPerformed

    private void btnPendapatanHarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendapatanHarianActionPerformed
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        DariTanggal = df.format(dcDari.getDate());
        SampaiTanggal = df.format(dcSampai.getDate());

        HashMap hm = new HashMap();

        hm.put("IdKaryawan", KaryawanID);
        hm.put("drTanggal", DariTanggal);
        hm.put("smpTanggal", SampaiTanggal);
        String ReportFile = null;

        ReportFile = ReportAdministration.getReportFile() + "StrukTransaksiKaryawan.jasper";

        try {
            ReportAdministration.printReport(Main.data.getActiveConnection(), ReportFile, hm, 0, 0, false);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPendapatanHarianActionPerformed

    /**
    * @param args the command line arguments
    */

    Object KaryawanID;

    String DariTanggal;
    String SampaiTanggal;

    Statement stmGetData;
    ResultSet rsGetData;
    
    void initData () {
        try {
            stmGetData = Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (SQLException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err initData()", JOptionPane.ERROR_MESSAGE);
        }
    }
    void Show_Browse_Karyawan () {
        SelectData karyawan=new SelectData(new Frame(), true) {

            @Override
            public void Select () {
                KaryawanID=tabel.getValueAt(tabel.getSelectedRow(), 0);
                txtNamaKaryawan.setText(tabel.getValueAt(tabel.getSelectedRow(), 1).toString());
                dispose();
            }
        };
        karyawan.setQuery("SELECT IDKARYAWAN, NAMAKARYAWAN FROM KARYAWAN() ORDER BY NAMAKARYAWAN");
        karyawan.LoadData();
        karyawan.show();
    }

    void nextfocus (KeyEvent evt) {
        try {
            int key = evt.getKeyCode();
            if (key==KeyEvent.VK_ENTER) {
                Robot r = new Robot();
                r.keyPress(KeyEvent.VK_TAB);
            }
        } catch (AWTException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel1;
    public static javax.swing.JButton btnBrowseKaryawan;
    private javax.swing.JButton btnPendapatan;
    private javax.swing.JButton btnPendapatanHarian;
    public static javax.swing.JButton btnPreviewMutasiDaftarKaryawan;
    public static javax.swing.JButton btnPreviewMutasiKeuangan;
    public static javax.swing.JCheckBox chkPerusahaan;
    private com.toedter.calendar.JDateChooser dcDari;
    private com.toedter.calendar.JDateChooser dcSampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelKaryawan;
    public static javax.swing.JTextField txtNamaKaryawan;
    // End of variables declaration//GEN-END:variables

}
