/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreviewLaporan_1.java
 *
 * Created on 18-Mar-2009, 15:24:44
 */

package com.salon.ui.form;

import com.salon.setting.Setting;
import com.salon.launcher.Main;
import com.salon.util.MyData;
import com.salon.util.ReportAdministration;
import com.salon.util.formSystematization;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author SAK
 */
public class PreviewLaporan_1 extends javax.swing.JDialog {

    /** Creates new form PreviewLaporan_1 */
    public PreviewLaporan_1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initData();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOrderBarang1 = new javax.swing.JPanel();
        cboDrTanggalPenjualan = new javax.swing.JComboBox();
        cboDrBulanPenjualan = new javax.swing.JComboBox();
        cboDrTahunPenjualan = new javax.swing.JComboBox();
        cboSmpTahunPenjualan = new javax.swing.JComboBox();
        cboSmpBulanPenjualan = new javax.swing.JComboBox();
        cboSmpTanggalPenjualan = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelKaryawan2 = new javax.swing.JPanel();
        txtNoPenjualanBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        chkNoPenjualan = new javax.swing.JCheckBox();
        btnPreviewPenjualan = new javax.swing.JButton();
        panelBukuTamu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelKaryawan3 = new javax.swing.JPanel();
        txtNoTamu = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        chkNoTamu = new javax.swing.JCheckBox();
        btnPreviewBukuTamu = new javax.swing.JButton();
        dcDariTamu = new com.toedter.calendar.JDateChooser();
        dcSampaiTamu = new com.toedter.calendar.JDateChooser();
        panelPerawatan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelKaryawan = new javax.swing.JPanel();
        txtNoPerawatan = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        chkNoPerawatan = new javax.swing.JCheckBox();
        btnPreviewPerawatan = new javax.swing.JButton();
        dcDariPerawatan = new com.toedter.calendar.JDateChooser();
        dcSampaiPerawatan = new com.toedter.calendar.JDateChooser();
        panelOrderBarang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelKaryawan1 = new javax.swing.JPanel();
        txtNoOrderBarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        chkNoOrder = new javax.swing.JCheckBox();
        btnPreviewOrder = new javax.swing.JButton();
        dcDariOrder = new com.toedter.calendar.JDateChooser();
        dcSampaiOrder = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelOrderBarang1.setBorder(javax.swing.BorderFactory.createTitledBorder("Penjualan Barang"));
        panelOrderBarang1.setEnabled(false);

        cboDrTanggalPenjualan.setEnabled(false);
        cboDrTanggalPenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDrTanggalPenjualanKeyPressed(evt);
            }
        });

        cboDrBulanPenjualan.setEnabled(false);
        cboDrBulanPenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDrBulanPenjualanKeyPressed(evt);
            }
        });

        cboDrTahunPenjualan.setEnabled(false);
        cboDrTahunPenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboDrTahunPenjualanKeyPressed(evt);
            }
        });

        cboSmpTahunPenjualan.setEnabled(false);
        cboSmpTahunPenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboSmpTahunPenjualanKeyPressed(evt);
            }
        });

        cboSmpBulanPenjualan.setEnabled(false);
        cboSmpBulanPenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboSmpBulanPenjualanKeyPressed(evt);
            }
        });

        cboSmpTanggalPenjualan.setEnabled(false);
        cboSmpTanggalPenjualan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboSmpTanggalPenjualanKeyPressed(evt);
            }
        });

        jLabel5.setText("Dari Tanggal : ");
        jLabel5.setEnabled(false);

        jLabel6.setText("Sampai Tanggal : ");
        jLabel6.setEnabled(false);

        panelKaryawan2.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Penjualan Barang : "));
        panelKaryawan2.setEnabled(false);

        txtNoPenjualanBarang.setEnabled(false);
        txtNoPenjualanBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPenjualanBarangKeyPressed(evt);
            }
        });

        jLabel14.setText("No. ID");
        jLabel14.setEnabled(false);

        javax.swing.GroupLayout panelKaryawan2Layout = new javax.swing.GroupLayout(panelKaryawan2);
        panelKaryawan2.setLayout(panelKaryawan2Layout);
        panelKaryawan2Layout.setHorizontalGroup(
            panelKaryawan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawan2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoPenjualanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKaryawan2Layout.setVerticalGroup(
            panelKaryawan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawan2Layout.createSequentialGroup()
                .addGroup(panelKaryawan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNoPenjualanBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkNoPenjualan.setText("No. ID Perawatan");
        chkNoPenjualan.setEnabled(false);
        chkNoPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoPenjualanActionPerformed(evt);
            }
        });

        btnPreviewPenjualan.setText("Preview Penjualan Barang");
        btnPreviewPenjualan.setEnabled(false);
        btnPreviewPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewPenjualanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOrderBarang1Layout = new javax.swing.GroupLayout(panelOrderBarang1);
        panelOrderBarang1.setLayout(panelOrderBarang1Layout);
        panelOrderBarang1Layout.setHorizontalGroup(
            panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBarang1Layout.createSequentialGroup()
                .addGroup(panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKaryawan2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBarang1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBarang1Layout.createSequentialGroup()
                                .addComponent(cboDrTanggalPenjualan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboDrBulanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboDrTahunPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBarang1Layout.createSequentialGroup()
                                .addComponent(cboSmpTanggalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSmpBulanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboSmpTahunPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(chkNoPenjualan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBarang1Layout.createSequentialGroup()
                        .addContainerGap(99, Short.MAX_VALUE)
                        .addComponent(btnPreviewPenjualan)))
                .addContainerGap())
        );
        panelOrderBarang1Layout.setVerticalGroup(
            panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBarang1Layout.createSequentialGroup()
                .addGroup(panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDrTanggalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDrTahunPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboDrBulanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrderBarang1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSmpTanggalPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSmpTahunPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboSmpBulanPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkNoPenjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKaryawan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreviewPenjualan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBukuTamu.setBorder(javax.swing.BorderFactory.createTitledBorder("Buku Tamu"));

        jLabel7.setText("Dari Tanggal : ");

        jLabel8.setText("Sampai Tanggal : ");

        panelKaryawan3.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Penjualan Barang : "));

        txtNoTamu.setEnabled(false);
        txtNoTamu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoTamuKeyPressed(evt);
            }
        });

        jLabel15.setText("No. ID");

        javax.swing.GroupLayout panelKaryawan3Layout = new javax.swing.GroupLayout(panelKaryawan3);
        panelKaryawan3.setLayout(panelKaryawan3Layout);
        panelKaryawan3Layout.setHorizontalGroup(
            panelKaryawan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawan3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKaryawan3Layout.setVerticalGroup(
            panelKaryawan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawan3Layout.createSequentialGroup()
                .addGroup(panelKaryawan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtNoTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkNoTamu.setText("No. ID Perawatan");
        chkNoTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoTamuActionPerformed(evt);
            }
        });

        btnPreviewBukuTamu.setText("Preview Buku Tamu");
        btnPreviewBukuTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewBukuTamuActionPerformed(evt);
            }
        });

        dcDariTamu.setDateFormatString("dd-MM-yyyy");

        dcSampaiTamu.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout panelBukuTamuLayout = new javax.swing.GroupLayout(panelBukuTamu);
        panelBukuTamu.setLayout(panelBukuTamuLayout);
        panelBukuTamuLayout.setHorizontalGroup(
            panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuTamuLayout.createSequentialGroup()
                .addGroup(panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKaryawan3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBukuTamuLayout.createSequentialGroup()
                        .addContainerGap(131, Short.MAX_VALUE)
                        .addComponent(btnPreviewBukuTamu))
                    .addGroup(panelBukuTamuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(15, 15, 15))
                    .addGroup(panelBukuTamuLayout.createSequentialGroup()
                        .addGroup(panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNoTamu)
                            .addGroup(panelBukuTamuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dcDariTamu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcSampaiTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelBukuTamuLayout.setVerticalGroup(
            panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBukuTamuLayout.createSequentialGroup()
                .addGroup(panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dcDariTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBukuTamuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBukuTamuLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(chkNoTamu))
                    .addComponent(dcSampaiTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(panelKaryawan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreviewBukuTamu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelPerawatan.setBorder(javax.swing.BorderFactory.createTitledBorder("Transaksi Perawatan / Penjualan"));

        jLabel1.setText("Dari Tanggal : ");

        jLabel2.setText("Sampai Tanggal : ");

        panelKaryawan.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Perawatan : "));

        txtNoPerawatan.setEnabled(false);
        txtNoPerawatan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoPerawatanKeyPressed(evt);
            }
        });

        jLabel12.setText("No. ID");

        javax.swing.GroupLayout panelKaryawanLayout = new javax.swing.GroupLayout(panelKaryawan);
        panelKaryawan.setLayout(panelKaryawanLayout);
        panelKaryawanLayout.setHorizontalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKaryawanLayout.setVerticalGroup(
            panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawanLayout.createSequentialGroup()
                .addGroup(panelKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNoPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkNoPerawatan.setText("No. ID Perawatan");
        chkNoPerawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoPerawatanActionPerformed(evt);
            }
        });

        btnPreviewPerawatan.setText("Preview Transaksi Perawatan");
        btnPreviewPerawatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewPerawatanActionPerformed(evt);
            }
        });

        dcDariPerawatan.setDateFormatString("dd-MM-yyyy");

        dcSampaiPerawatan.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout panelPerawatanLayout = new javax.swing.GroupLayout(panelPerawatan);
        panelPerawatan.setLayout(panelPerawatanLayout);
        panelPerawatanLayout.setHorizontalGroup(
            panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerawatanLayout.createSequentialGroup()
                .addGroup(panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKaryawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerawatanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dcDariPerawatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dcSampaiPerawatan, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                    .addComponent(chkNoPerawatan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerawatanLayout.createSequentialGroup()
                        .addContainerGap(83, Short.MAX_VALUE)
                        .addComponent(btnPreviewPerawatan)))
                .addContainerGap())
        );
        panelPerawatanLayout.setVerticalGroup(
            panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerawatanLayout.createSequentialGroup()
                .addGroup(panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(dcDariPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerawatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerawatanLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkNoPerawatan))
                    .addComponent(dcSampaiPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreviewPerawatan))
        );

        panelOrderBarang.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Barang"));

        jLabel3.setText("Dari Tanggal : ");

        jLabel4.setText("Sampai Tanggal : ");

        panelKaryawan1.setBorder(javax.swing.BorderFactory.createTitledBorder("No. Order Barang : "));

        txtNoOrderBarang.setEnabled(false);
        txtNoOrderBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNoOrderBarangKeyPressed(evt);
            }
        });

        jLabel13.setText("No. ID");

        javax.swing.GroupLayout panelKaryawan1Layout = new javax.swing.GroupLayout(panelKaryawan1);
        panelKaryawan1.setLayout(panelKaryawan1Layout);
        panelKaryawan1Layout.setHorizontalGroup(
            panelKaryawan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawan1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNoOrderBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelKaryawan1Layout.setVerticalGroup(
            panelKaryawan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKaryawan1Layout.createSequentialGroup()
                .addGroup(panelKaryawan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNoOrderBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkNoOrder.setText("No. ID Order Barang");
        chkNoOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNoOrderActionPerformed(evt);
            }
        });

        btnPreviewOrder.setText("Preview Order Barang");
        btnPreviewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewOrderActionPerformed(evt);
            }
        });

        dcDariOrder.setDateFormatString("dd-MM-yyyy");

        dcSampaiOrder.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout panelOrderBarangLayout = new javax.swing.GroupLayout(panelOrderBarang);
        panelOrderBarang.setLayout(panelOrderBarangLayout);
        panelOrderBarangLayout.setHorizontalGroup(
            panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBarangLayout.createSequentialGroup()
                .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelKaryawan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBarangLayout.createSequentialGroup()
                        .addContainerGap(117, Short.MAX_VALUE)
                        .addComponent(btnPreviewOrder))
                    .addGroup(panelOrderBarangLayout.createSequentialGroup()
                        .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOrderBarangLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addComponent(chkNoOrder)
                            .addGroup(panelOrderBarangLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcSampaiOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcDariOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelOrderBarangLayout.setVerticalGroup(
            panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBarangLayout.createSequentialGroup()
                .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dcDariOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrderBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOrderBarangLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(1, 1, 1)
                        .addComponent(chkNoOrder))
                    .addComponent(dcSampaiOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelKaryawan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPreviewOrder)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPerawatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOrderBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(panelOrderBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBukuTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelOrderBarang, 0, 192, Short.MAX_VALUE)
                    .addComponent(panelPerawatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOrderBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelBukuTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    String DariTanggal;
    String SampaiTanggal;

    Statement stmGetData;
    ResultSet rsGetData;

    void initData () {
        MyData.setDateCombo(cboDrTanggalPenjualan, cboDrBulanPenjualan, cboDrTahunPenjualan);
        MyData.setDateCombo(cboSmpTanggalPenjualan, cboSmpBulanPenjualan, cboSmpTahunPenjualan);

        try {
            stmGetData=Main.data.getActiveConnection().createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        } catch (SQLException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err initData()", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void cboDrTanggalPenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDrTanggalPenjualanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboDrTanggalPenjualanKeyPressed

    private void cboDrBulanPenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDrBulanPenjualanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboDrBulanPenjualanKeyPressed

    private void cboDrTahunPenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboDrTahunPenjualanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboDrTahunPenjualanKeyPressed

    private void cboSmpTahunPenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboSmpTahunPenjualanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboSmpTahunPenjualanKeyPressed

    private void cboSmpBulanPenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboSmpBulanPenjualanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboSmpBulanPenjualanKeyPressed

    private void cboSmpTanggalPenjualanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboSmpTanggalPenjualanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_cboSmpTanggalPenjualanKeyPressed

    private void txtNoPenjualanBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPenjualanBarangKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNoPenjualanBarangKeyPressed

    private void chkNoPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoPenjualanActionPerformed
        txtNoPenjualanBarang.setEnabled(chkNoPenjualan.isSelected());
        cboDrTanggalPenjualan.setEnabled(chkNoPenjualan.isSelected()==false);
        cboDrBulanPenjualan.setEnabled(chkNoPenjualan.isSelected()==false);
        cboDrTahunPenjualan.setEnabled(chkNoPenjualan.isSelected()==false);
        cboSmpTanggalPenjualan.setEnabled(chkNoPenjualan.isSelected()==false);
        cboSmpBulanPenjualan.setEnabled(chkNoPenjualan.isSelected()==false);
        cboSmpTahunPenjualan.setEnabled(chkNoPenjualan.isSelected()==false);
}//GEN-LAST:event_chkNoPenjualanActionPerformed

    private void btnPreviewPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewPenjualanActionPerformed
        
        HashMap hm = new HashMap();

        String ReportFile = null;
        if (chkNoPenjualan.isSelected()==false) {
            ReportFile = ReportAdministration.getReportFile() + "penjualan_pertanggal.jasper";

            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            DariTanggal = MyData.setDateString(cboDrTanggalPenjualan, cboDrBulanPenjualan, cboDrTahunPenjualan);
            SampaiTanggal = MyData.setDateString(cboSmpTanggalPenjualan, cboSmpBulanPenjualan, cboSmpTahunPenjualan);

            hm.put("drtanggal", DariTanggal);
            hm.put("smptanggal", SampaiTanggal);
        }else {
            ReportFile = ReportAdministration.getReportFile() + "penjualan_perid.jasper";

            hm.put("transaksiid", txtNoPenjualanBarang.getText());
        }
        hm.put("cabangid", Setting.CabangID);
        try {
            ReportAdministration.runReport(Main.data.getActiveConnection(), ReportFile, hm);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            try {
                Main.data.roolback();
            } catch (SQLException ex1) {
                Logger.getLogger(PreviewLaporan_1.class.getName()).log(Level.SEVERE, null, ex1);
            }
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPreviewPenjualanActionPerformed

    private void txtNoTamuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoTamuKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNoTamuKeyPressed

    private void chkNoTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoTamuActionPerformed
        txtNoTamu.setEnabled(chkNoTamu.isSelected());
        dcDariTamu.setEnabled(chkNoTamu.isSelected()==false);
        dcSampaiTamu.setEnabled(chkNoTamu.isSelected()==false);
}//GEN-LAST:event_chkNoTamuActionPerformed

    private void btnPreviewBukuTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewBukuTamuActionPerformed
        
}//GEN-LAST:event_btnPreviewBukuTamuActionPerformed

    private void txtNoPerawatanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoPerawatanKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNoPerawatanKeyPressed

    private void chkNoPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoPerawatanActionPerformed
        txtNoPerawatan.setEnabled(chkNoPerawatan.isSelected());
        dcDariPerawatan.setEnabled(chkNoPerawatan.isSelected()==false);
        dcSampaiPerawatan.setEnabled(chkNoPerawatan.isSelected()==false);

    }//GEN-LAST:event_chkNoPerawatanActionPerformed

    private void btnPreviewPerawatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewPerawatanActionPerformed

        HashMap hm = new HashMap();

        String ReportFile = null;
        if (chkNoPerawatan.isSelected()==false) {
            ReportFile = ReportAdministration.getReportFile() + "perawatan_pertanggal.jasper";

            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            DariTanggal = df.format(dcDariPerawatan.getDate());
            SampaiTanggal = df.format(dcSampaiPerawatan.getDate());


            hm.put("drtanggal", DariTanggal);
            hm.put("smptanggal", SampaiTanggal);
        }else {
            ReportFile = ReportAdministration.getReportFile() + "perawatan_perid.jasper";

            hm.put("transaksiid", txtNoPerawatan.getText());
        }
        hm.put("cabangid", Setting.CabangID);
        hm.put("SUBREPORT_DIR", ReportAdministration.getReportFile());//String.class.getResourceAsStream(ReportAdministration.getReportFile()));

        try {
            ReportAdministration.runReport(Main.data.getActiveConnection(), ReportFile, hm);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPreviewPerawatanActionPerformed

    private void txtNoOrderBarangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoOrderBarangKeyPressed
        formSystematization.nextfocus(evt);
}//GEN-LAST:event_txtNoOrderBarangKeyPressed

    private void chkNoOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNoOrderActionPerformed
        txtNoOrderBarang.setEnabled(chkNoOrder.isSelected());
        dcDariOrder.setEnabled(chkNoOrder.isSelected()==false);
        dcSampaiOrder.setEnabled(chkNoOrder.isSelected()==false);
}//GEN-LAST:event_chkNoOrderActionPerformed

    private void btnPreviewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewOrderActionPerformed

        HashMap hm = new HashMap();

        String ReportFile = null;
        if (chkNoOrder.isSelected()==false) {
            ReportFile = ReportAdministration.getReportFile() + "order_pertanggal.jasper";

            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            DariTanggal = df.format(dcDariOrder.getDate());
            SampaiTanggal = df.format(dcSampaiOrder.getDate());
            
            hm.put("drtanggal", DariTanggal);
            hm.put("smptanggal", SampaiTanggal);
        }else {
            ReportFile = ReportAdministration.getReportFile() + "order_perid.jasper";

            hm.put("transaksiid", txtNoOrderBarang.getText());
        }
        hm.put("cabangid", Setting.CabangID);
        try {
            ReportAdministration.runReport(Main.data.getActiveConnection(), ReportFile, hm);
        } catch (JRException ex) {
            Logger.getLogger(PreviewLaporan.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, ex, "err : Preview", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_btnPreviewOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreviewBukuTamu;
    private javax.swing.JButton btnPreviewOrder;
    private javax.swing.JButton btnPreviewPenjualan;
    private javax.swing.JButton btnPreviewPerawatan;
    private javax.swing.JComboBox cboDrBulanPenjualan;
    private javax.swing.JComboBox cboDrTahunPenjualan;
    private javax.swing.JComboBox cboDrTanggalPenjualan;
    private javax.swing.JComboBox cboSmpBulanPenjualan;
    private javax.swing.JComboBox cboSmpTahunPenjualan;
    private javax.swing.JComboBox cboSmpTanggalPenjualan;
    private javax.swing.JCheckBox chkNoOrder;
    private javax.swing.JCheckBox chkNoPenjualan;
    private javax.swing.JCheckBox chkNoPerawatan;
    private javax.swing.JCheckBox chkNoTamu;
    private com.toedter.calendar.JDateChooser dcDariOrder;
    private com.toedter.calendar.JDateChooser dcDariPerawatan;
    private com.toedter.calendar.JDateChooser dcDariTamu;
    private com.toedter.calendar.JDateChooser dcSampaiOrder;
    private com.toedter.calendar.JDateChooser dcSampaiPerawatan;
    private com.toedter.calendar.JDateChooser dcSampaiTamu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel panelBukuTamu;
    private javax.swing.JPanel panelKaryawan;
    private javax.swing.JPanel panelKaryawan1;
    private javax.swing.JPanel panelKaryawan2;
    private javax.swing.JPanel panelKaryawan3;
    private javax.swing.JPanel panelOrderBarang;
    private javax.swing.JPanel panelOrderBarang1;
    private javax.swing.JPanel panelPerawatan;
    private javax.swing.JTextField txtNoOrderBarang;
    private javax.swing.JTextField txtNoPenjualanBarang;
    private javax.swing.JTextField txtNoPerawatan;
    private javax.swing.JTextField txtNoTamu;
    // End of variables declaration//GEN-END:variables

}
